import type Database from 'better-sqlite3';
import type { Tag, TagWithCount } from '../../shared/contracts/tag.types';

interface TagRow {
  id: number;
  name: string;
  color: string;
}

/**
 * Generate a stable HSL color from a tag name.
 * Uses same algorithm as renderer's tagColor for consistency.
 */
function tagColor(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  }
  const hue = ((hash % 360) + 360) % 360;
  return `hsl(${hue}, 55%, 72%)`;
}

export class TagStore {
  constructor(private readonly db: Database.Database) {}

  /**
   * Find a tag by name or create it if it doesn't exist.
   * Auto-generates color for new tags.
   */
  findOrCreate(name: string): Tag {
    const trimmed = name.trim();
    // First try to find existing
    const existing = this.db.prepare(
      'SELECT * FROM tag WHERE name = ?',
    ).get(trimmed) as TagRow | undefined;
    if (existing) return toTag(existing);

    // Create new tag with auto-generated color
    const color = tagColor(trimmed);
    const result = this.db.prepare(
      'INSERT INTO tag (name, color) VALUES (?, ?)',
    ).run(trimmed, color);
    const created = this.db.prepare(
      'SELECT * FROM tag WHERE id = ?',
    ).get(result.lastInsertRowid) as TagRow | undefined;
    if (!created) throw new Error('Failed to create tag.');
    return toTag(created);
  }

  /**
   * List all tags for a given entry, ordered by tag name.
   */
  listByEntry(entryId: number): Tag[] {
    const rows = this.db.prepare(`
      SELECT t.id, t.name, t.color
      FROM tag t
      INNER JOIN entry_tag et ON et.tagId = t.id
      WHERE et.entryId = ?
      ORDER BY t.name ASC
    `).all(entryId) as TagRow[];
    return rows.map(toTag);
  }

  /**
   * Associate a tag with an entry (idempotent — no-op if already linked).
   *
   * @param source - 'manual' (user-typed) or 'auto' (AI-generated, Tag Agent).
   */
  tagEntry(entryId: number, tagId: number, source: 'manual' | 'auto' = 'manual'): void {
    this.db.prepare(`
      INSERT OR IGNORE INTO entry_tag (entryId, tagId, source, createdAt)
      VALUES (?, ?, ?, ?)
    `).run(entryId, tagId, source, new Date().toISOString());
  }

  /**
   * Remove a tag association from an entry.
   */
  /** Mark whether the entry's tags were generated by AI. */
  setAiTagGenerated(entryId: number, generated: boolean): void {
    this.db.prepare(
      'UPDATE entry SET aiTagGenerated = ? WHERE id = ?',
    ).run(generated ? 1 : 0, entryId);
  }

  /** Check whether the entry has been AI-tagged. */
  isAiTagGenerated(entryId: number): boolean {
    const row = this.db.prepare(
      'SELECT aiTagGenerated FROM entry WHERE id = ?',
    ).get(entryId) as { aiTagGenerated: number } | undefined;
    return row ? row.aiTagGenerated === 1 : false;
  }

  untagEntry(entryId: number, tagId: number): void {
    this.db.prepare(`
      DELETE FROM entry_tag WHERE entryId = ? AND tagId = ?
    `).run(entryId, tagId);
  }

  /**
   * Return all tags with their associated entry count, ordered by count DESC, name ASC.
   */
  listAllWithCount(): TagWithCount[] {
    const rows = this.db.prepare(`
      SELECT t.id, t.name, t.color, COUNT(et.entryId) AS count
      FROM tag t
      INNER JOIN entry_tag et ON t.id = et.tagId
      INNER JOIN entry e ON e.id = et.entryId AND e.isDeleted = 0
      GROUP BY t.id
      ORDER BY count DESC, t.name ASC
    `).all() as Array<TagRow & { count: number }>;
    return rows.map((row) => ({ ...toTag(row), count: row.count }));
  }

  /**
   * Return all tags that are used by at least one entry (count >= 1)
   * but NOT associated with the given entry.
   */
  listAvailableForEntry(entryId: number): TagWithCount[] {
    const rows = this.db.prepare(`
      SELECT t.id, t.name, t.color, COUNT(et.entryId) AS count
      FROM tag t
      INNER JOIN entry_tag et ON t.id = et.tagId
      INNER JOIN entry e ON e.id = et.entryId AND e.isDeleted = 0
      WHERE t.id NOT IN (
        SELECT et2.tagId FROM entry_tag et2 WHERE et2.entryId = ?
      )
      GROUP BY t.id
      ORDER BY count DESC, t.name ASC
    `).all(entryId) as Array<TagRow & { count: number }>;
    return rows.map((row) => ({ ...toTag(row), count: row.count }));
  }
}

function toTag(row: TagRow): Tag {
  return { id: row.id, name: row.name, color: row.color };
}